#!/usr/bin/env bash
# Le scan.json gerado pelo Socket CLI e cria issues GitHub pra cada finding
# de severity >= high que ainda nao tem issue aberta.
#
# Dedup: titulo deterministico `[socket] <type>: <pkg>@<ver>`.
# Se issue ja aberta com mesmo titulo, pula.
# Se foi closed e o problema voltou, recria (sinal de regressao).

set -euo pipefail

SCAN_FILE="${SCAN_FILE:-scan.json}"

if [ ! -f "$SCAN_FILE" ]; then
  echo "::error::$SCAN_FILE nao encontrado"
  exit 1
fi

# Severity threshold: ajuste pra incluir 'medium' se quiser mais cobertura
SEVERITIES='["critical", "high"]'

# Garante que os labels existem (idempotente — gh label create falha se ja existir, ignoramos)
gh label create socket-finding --color "d73a4a" --description "Auto-criada via socket-issues.yml" 2>/dev/null || true
gh label create "severity:critical" --color "b60205" --description "Severity: critical" 2>/dev/null || true
gh label create "severity:high" --color "d93f0b" --description "Severity: high" 2>/dev/null || true

# Cache existing open issues pra dedup (1 API call vs N)
gh issue list --label socket-finding --state open --json title --limit 200 \
  | jq -r '.[].title' > existing_titles.txt

# Extract alerts. Socket scan view retorna { ok: true, data: [{ name, version, alerts: [...] }, ...] }.
# Aceita tambem .artifacts[].alerts (formato alternativo) como fallback defensivo.
# Cada alert eh enriquecido com package/version do artifact pai pra titulo do issue.
jq -c --argjson sev "$SEVERITIES" '
  ((.data // .artifacts // []) | select(type == "array") | .[]) as $art
  | ($art.alerts // []) | .[]
  | . + {
      package: ($art.name // $art.package // "unknown"),
      version: ($art.version // ""),
    }
  | select(.severity as $s | $sev | index($s))
' "$SCAN_FILE" > filtered_alerts.jsonl 2>/dev/null || true

if [ ! -s filtered_alerts.jsonl ]; then
  echo "::notice::Nenhum alert de severity high/critical encontrado"
  echo "Conteudo do scan (primeiros 1500 chars):"
  head -c 1500 "$SCAN_FILE"
  exit 0
fi

echo "::notice::Encontrados $(wc -l < filtered_alerts.jsonl) alerts severity high/critical"

count=0
while IFS= read -r alert; do
  type=$(echo "$alert" | jq -r '.type // "unknown"')
  severity=$(echo "$alert" | jq -r '.severity // "unknown"')
  pkg=$(echo "$alert" | jq -r '.package // .pkg // "unknown"')
  ver=$(echo "$alert" | jq -r '.version // .ver // ""')
  description=$(echo "$alert" | jq -r '.description // .message // ""')

  if [ -n "$ver" ] && [ "$ver" != "null" ]; then
    title="[socket] $type: $pkg@$ver"
  else
    title="[socket] $type: $pkg"
  fi

  if grep -Fxq "$title" existing_titles.txt; then
    echo "skip: $title (ja aberta)"
    continue
  fi

  # Build body num arquivo temp pra evitar problemas com heredoc/escape
  body_file=$(mktemp)
  {
    printf '**Severity:** `%s`\n' "$severity"
    printf '**Type:** `%s`\n' "$type"
    if [ -n "$ver" ] && [ "$ver" != "null" ]; then
      printf '**Package:** `%s@%s`\n\n' "$pkg" "$ver"
    else
      printf '**Package:** `%s`\n\n' "$pkg"
    fi
    printf '%s\n\n' "$description"
    printf -- '---\n\n'
    printf '<details>\n<summary>Raw alert (JSON)</summary>\n\n```json\n'
    echo "$alert" | jq .
    printf '\n```\n\n</details>\n\n'
    printf '🤖 Auto-generated by [`socket-issues.yml`](../actions/workflows/socket-issues.yml). Close se for falso positivo.\n'
  } > "$body_file"

  if gh issue create \
    --title "$title" \
    --body-file "$body_file" \
    --label "socket-finding" \
    --label "severity:$severity"; then
    count=$((count + 1))
  else
    echo "::warning::Falha ao criar issue: $title"
  fi

  rm -f "$body_file"
done < filtered_alerts.jsonl

echo "::notice::Criadas $count novas issues a partir do scan Socket"
